#image: Visual Studio 2017
#configuration: Debug
#install:
#- ps: $env:Path = ""
before_build:
  - nuget restore
  
build:
  #publish_wap_beanstalk: true
  verbosity: minimal
  
#after_build:
  #- 7z a myapp.zip C:\projects\ecommercesite\eCommerceSite\bin\eCommerceSite.dll
  
artifacts:
  - path: C:\projects\ecommercesite\eCommerceSite\bin\eCommerceSite.dll
    name: myapp
    type: ElasticBeanstalkPackage
